import { useEffect, useState } from "react";
import { apiPath, getAppPath } from "../lib/api.js";

type FactStatus = "confirmed" | "estimated" | "needs_input" | "missing";
type Step = { id: string; title: string; status: "ready_to_prepare" | "blocked"; detail: string; requiredFacts: string[]; requiredAuthorization: string[] };
type Report = { summary: string; executionReadiness: "blocked_pending_store_facts" | "blocked_pending_authorized_knowledge"; actionMode: "draft_only"; factStatuses: Array<{ field: string; status: FactStatus }>; requiredKnowledge: string[]; steps: Step[]; safetyBoundaries: string[] };

const fieldLabels: Record<string, string> = { storeName: "门店名称", city: "所在城市", storeType: "门店类型", mainServices: "主营服务", monthlyNewCustomersRange: "月新增客户区间", repeatPurchaseRateRange: "复购率区间", primaryChannels: "主要获客渠道", currentChallenges: "当前经营难题" };

function headers(): HeadersInit { const token = localStorage.getItem("store_os_token"); return token ? { Authorization: `Bearer ${token}` } : {}; }

export function LanqiExecutionPlanPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { if (!localStorage.getItem("store_os_token")) { localStorage.setItem("store_os_post_login_redirect", window.location.pathname); window.location.replace(getAppPath("/login")); return; } void loadReport(); }, []);
  async function loadReport() { setLoading(true); setError(""); try { const response = await fetch(apiPath("/lanqi/execution-plan/current"), { headers: headers() }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? body.error ?? "执行方案草案暂时无法加载，请稍后重试。"); setReport(body.report as Report); } catch (cause) { setError(cause instanceof Error ? cause.message : "执行方案草案加载失败。"); } finally { setLoading(false); } }
  const factGaps = report?.factStatuses.filter(item => item.status === "needs_input" || item.status === "missing") ?? [];
  return <div className="lanqiExecutionPage"><header className="lanqiExecutionHeader"><button className="lanqiExecutionBrand" onClick={() => window.location.href = getAppPath("/my-ai")}>兰琪美业 <span>经营增长系统</span></button><div><button onClick={() => window.location.href = getAppPath("/lanqi/diagnosis")}>经营诊断</button><button onClick={() => window.location.href = getAppPath("/lanqi/store-profile")}>经营档案</button></div></header><main className="lanqiExecutionMain"><section className="lanqiExecutionHero"><p>LANQI AI · DRAFT ONLY</p><h1>项目、获客与成交</h1><span>先完成事实核对和兰琪授权知识接入，再生成可确认的执行方案。</span></section>{loading && <section className="lanqiExecutionLoading">正在整理本门店的方案准备状态…</section>}{error && <section className="lanqiExecutionError">{error}<button onClick={() => void loadReport()}>重新加载</button></section>}{report && <><section className="lanqiExecutionSummary"><div><small>当前状态</small><h2>{report.summary}</h2></div><span>{report.executionReadiness === "blocked_pending_store_facts" ? "待补门店资料" : "待接入兰琪授权知识"}</span></section><section className="lanqiDraftFence"><strong>仅草案模式</strong><p>本页不会执行投放、发消息、付款、发布或其他外部动作；也不会把推荐关系当作其他门店的数据访问权。</p></section><section className="lanqiExecutionGrid"><article><div className="sectionKicker">STORE FACTS</div><h2>本店准备清单</h2>{factGaps.length ? <><p>以下信息需由门店补齐或核实，系统不会自行补写。</p><div className="lanqiTagList">{factGaps.map(item => <span key={item.field}>{fieldLabels[item.field] ?? item.field}</span>)}</div></> : <p>基础资料已齐备，可进入授权方案的确认准备。</p>}<button onClick={() => window.location.href = getAppPath("/lanqi/store-profile")}>查看并完善经营档案</button></article><article><div className="sectionKicker">LANQI AUTHORIZATION</div><h2>需要兰琪提供</h2><p>以下内容须由兰琪按门店适用范围授权并确认后接入。</p><div className="lanqiKnowledgeList">{report.requiredKnowledge.map(item => <div key={item}>{item}<span>待接入</span></div>)}</div></article></section><section className="lanqiPlanSteps"><div className="sectionKicker">PLAN FRAMEWORK</div><h2>执行方案草案框架</h2>{report.steps.map((step, index) => <article key={step.id} className={step.status}><div className="lanqiStepNumber">0{index + 1}</div><div><span>{step.status === "ready_to_prepare" ? "可准备" : "已锁定"}</span><h3>{step.title}</h3><p>{step.detail}</p>{step.requiredFacts.length > 0 && <small>待核对资料：{step.requiredFacts.map(field => fieldLabels[field] ?? field).join("、")}</small>}{step.requiredAuthorization.length > 0 && <small>所需授权：{step.requiredAuthorization.join("、")}</small>}</div></article>)}</section><section className="lanqiExecutionBoundary"><h2>当前边界</h2>{report.safetyBoundaries.map(item => <p key={item}>{item}</p>)}</section></>}</main></div>;
}
